from pathlib import Path

from snapshot_diff_kit import compare_dirs, should_ignore


def _write(root: Path, rel: str, content: str) -> None:
    p = root / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")


def test_should_ignore_suffix_pattern():
    assert should_ignore(Path("a/b/file.pyc"), ["*.pyc"])
    assert not should_ignore(Path("a/b/file.py"), ["*.pyc"])


def test_should_ignore_path_component():
    assert should_ignore(Path("a/.git/HEAD"), [".git"])
    assert not should_ignore(Path("a/gitignore_notes.txt"), [".git"])


def test_compare_dirs_detects_added(tmp_path):
    left = tmp_path / "left"
    right = tmp_path / "right"
    _write(left, "a.txt", "hello")
    _write(right, "a.txt", "hello")
    _write(left, "b.txt", "new file")

    deleted, added, modified = compare_dirs(left, right, [])

    assert deleted == []
    assert added == [Path("b.txt")]
    assert modified == []


def test_compare_dirs_detects_physical_deletion(tmp_path):
    left = tmp_path / "left"
    right = tmp_path / "right"
    _write(left, "a.txt", "hello")
    _write(right, "a.txt", "hello")
    _write(right, "gone.txt", "was here")

    deleted, added, modified = compare_dirs(left, right, [])

    assert deleted == [Path("gone.txt")]
    assert added == []
    assert modified == []


def test_compare_dirs_detects_content_modification(tmp_path):
    left = tmp_path / "left"
    right = tmp_path / "right"
    _write(left, "a.txt", "version 2")
    _write(right, "a.txt", "version 1")

    deleted, added, modified = compare_dirs(left, right, [])

    assert deleted == []
    assert added == []
    assert modified == [Path("a.txt")]


def test_compare_dirs_ignore_for_right_excludes_only_right_side(tmp_path):
    left = tmp_path / "left"
    right = tmp_path / "right"
    _write(left, "a.txt", "hello")
    _write(right, "a.txt", "hello")
    _write(right, "readme/notes.md", "generated by a previous run")

    deleted, added, modified = compare_dirs(left, right, [], ignore_for_right=["readme"])

    assert deleted == []
    assert added == []
    assert modified == []


def test_compare_dirs_ignore_patterns_apply_to_both_sides(tmp_path):
    left = tmp_path / "left"
    right = tmp_path / "right"
    _write(left, "a.txt", "hello")
    _write(right, "a.txt", "hello")
    _write(left, "cache/x.pyc", "compiled")

    deleted, added, modified = compare_dirs(left, right, ["*.pyc"])

    assert deleted == []
    assert added == []
    assert modified == []
